baseURL: /
theme: hugo-serif-theme
languageCode: en-us
title: Asia-Pacific Information Superhighway Platform. 
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  colors:
    black: '#2f2f41'
    grey: '#5C5A5A'
    primary: '#009edb'
    white: '#ffffff'
    white_offset: '#f6f7ff'
  fonts:
    base: Source Sans Pro
    google_fonts: https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap
    heading: Playfair Display
  footer:
    copyright_text: © United Nations ESCAP 2017-2022 
  google_analytics_id: ''
  google_tag_manager_id: ''
  homepage:
    show_contact_box: yes
    show_services_button: yes
  logo:
    alt: AP-IS - A United Nations ESCAP Initiative
    desktop: images/logo/UNESCAP_75.png
    desktop_height: 76px
    mobile: images/logo/SDG_Decade_of_Action.png
    mobile_height: 36px
  seo:
    meta_og_image: images/apis_screenshot.png
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  services:
    summary_truncate: 120
  team:
    summary_large_truncate: 120
menu:
  footer:
    - name: ESCAP Web Site
      url: "https://www.unescap.org/"
      weight: 1
    - name: UN Web Site
      url: "https://www.un.org/"
      weight: 2
    - name: UN Web Site Locator
      url: "https://unsceb.org/"
      weight: 3
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Events
      url: /services/
      weight: 3
    - name: Partners
      url: /team/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
